cosmosgl/graph

README.md
src/index.ts
src/modules/GraphData/index.ts
src/modules/Points/color-buffer.ts
src/modules/Store/index.ts

Logic tweaks of the API methods `selectNodesByIds` and `selectNodesByIndices`:
- all nodes are greyed out if `ids`/`indices` is an empty array,
- unselect all nodes if `ids`/`indices` are null.
Added second argument to the `selectNodeById` and `selectNodeByIndex` API methods. When set to `true`, selects adjacent nodes. The default is `false`.
Added a new API method `getAdjacentNodes`.

Node selection logic tweaks

---

README.md
src/index.ts
src/modules/Points/index.ts
src/modules/Points/track-positions.frag
src/modules/Points/tracked-buffer.ts

New API added:
- `trackNodesByIds`,
- `trackNodesByIndices` and
- `getTrackedNodePositionsMap`.
Allows to track the current coordinates X and Y of multiple nodes by their ids or indices. It is then more efficient to get the coordinates of the tracked nodes.

Tracking the current position of multiple nodes

---

src/config.ts
src/index.ts
src/modules/ForceCenter/index.ts
src/modules/ForceGravity/index.ts
src/modules/ForceLink/index.ts
src/modules/ForceManyBody/index.ts
src/modules/ForceManyBodyQuadtree/index.ts
src/modules/ForceMouse/index.ts
src/modules/GraphData/index.ts
src/modules/Lines/index.ts
src/modules/Points/color-buffer.ts
src/modules/Points/index.ts
src/modules/Points/size-buffer.ts
src/modules/Zoom/index.ts
src/modules/core-module.ts
src/types.ts

Cleaned up the input nodes and links types from `[key: string]: unknown;`.
Also renamed `InputNode` to `CosmosInputNode` and `InputLink` to `CosmosInputLink`.

Cleaned up the input nodes and links types

---

README.md
src/index.ts
src/modules/Zoom/index.ts
src/variables.ts

Methods `zoomToNodeById` and `zoomToNodeByIndex` now have a `scale` argument, which specifies the level of zooming.
In addition, the `canZoomOut` argument prevents zooming out from the node, if set `false`.
graph.<b>zoomToNodeById</b>(<i>id</i>, [<i>duration</i>], [<i>scale</i>], [<i>canZoomOut</i>])
and
graph.<b>zoomToNodeByIndex</b>(<i>index</i>, [<i>duration</i>], [<i>scale</i>], [<i>canZoomOut</i>])

Zoom to node with custom scale value

---

src/index.ts
src/modules/Points/draw-highlighted.frag
src/modules/Points/draw-highlighted.vert
src/modules/Points/index.ts
src/modules/Store/index.ts
src/variables.ts

Highlighted ring for the node will appear when you click on the node or select the node by its id (or index).
On background click as well as on select by nodes ids (or indices) and by the area highlighted ring will disappear.

Tweaking node highlighting logic

---

src/index.ts
src/modules/Points/index.ts

Hovering over a node with a zero index did not work:
https://user-images.githubusercontent.com/8654114/222089909-5b71b41f-2e4f-4b6e-a15c-27ba3b99bca4.mov
Fixed in this PR. Also added a minor tweak in creating random `X` and `Y` coordinates.

Fixed hovering over a node with a zero index

---

README.md
src/index.ts

The name of the method `trackNodesByIds` sounds a bit confusing (#43). Let's rename it to `trackNodePositionsByIds` (same for `trackNodePositionsByIndices`).

Renaming: `trackNodesBy...` -> `trackNodePositionsBy...`

---

src/modules/ForceCenter/index.ts
src/modules/ForceLink/index.ts
src/modules/ForceManyBody/index.ts
src/modules/ForceManyBodyQuadtree/index.ts
src/modules/Lines/index.ts
src/modules/Points/index.ts
src/modules/Shared/buffer.ts

Regl.js throws an error if the Buffers or Framebuffers are destroyed twice in a row.
Added method that checks if the Buffers or Framebuffers have already been destroyed.

Fixed Regl.js Buffers and Framebuffers double destruction

---

src/config.ts
src/index.ts

If the node is hovered, then a second, third and forth arguments appear in the `onTick` callback: `(alpha: number, node: Node | undefined, index: number | undefined, nodePosition: [number, number] | undefined) => void`.

New arguments for the `onTick` callback

---

src/index.ts
src/modules/Points/draw-highlighted.frag
src/modules/Points/draw-highlighted.vert
src/modules/Points/index.ts

This pull request includes the following changes:
1. A second optional argument, `focusedNodeId`, has been added to the `selectNodesByIds` and `selectNodesByIndices` methods. When a node is focused, a ring will be drawn around it as if the node had been clicked.
2. The transparency of the selected node's ring has been adjusted to inherit from the parent node.

Enhancement for highlighted node ring

---

README.md
src/config.ts
src/index.ts
src/modules/ForceLink/index.ts
src/modules/ForceManyBody/index.ts
src/modules/ForceManyBodyQuadtree/index.ts
src/modules/Points/index.ts
src/modules/Store/index.ts

1. Prevents Cosmos from crashing if there are no nodes or links. (Patch)
2. Updates space and screen size when `spaceSize` configuration parameter is changed or before the zoom in/out transformation occurs, and fixes the `fitView` when called before animation starts. (Patch)
3. Prevents Cosmos from crashing when the `spaceSize` configuration parameter exceeds the WebGL limit. (Patch)
4. Resetting the focused and hovered node after `graph.setData()`. (Patch)
5. New methods (`setFocusedNodeById` and `setFocusedNodeByIndex`) and config parameters (`renderHoveredNodeRing`, `hoveredNodeRingColor` and `focusedNodeRingColor`). (Minor)

Improvements and Bug Fixes

---

src/index.ts

Cosmos would not run simulation and render if there were no links. Fixed it:
https://github.com/cosmograph-org/cosmos/assets/8654114/0efa8be5-46c3-440b-8d7a-fb230d800733

Running the simulation and rendering the graph without links

---

src/index.ts

This change makes the `graph` field public in the main `Graph` class. The `graph` itself is a class where data processing happens. By making the `graph` field public, users can access its properties and methods directly, which may be useful in certain cases.

Make `graph` field public for advanced use

---

src/config.ts
src/index.ts
src/modules/ForceGravity/index.ts
src/modules/ForceManyBody/index.ts
src/modules/ForceManyBodyQuadtree/index.ts
src/modules/Lines/index.ts
src/modules/Points/index.ts
src/modules/Store/index.ts

If the `spaceSize` configuration value was outside the WebGL limits, it resulted in unnecessary graph updates on the next config update.

Keep the `spaceSize` configuration parameter stable

---

src/config.ts
src/helper.ts

Also removed the unused `StringAccessor` type.

Make the second argument `i` of the `NumericAccessor` and `ColorAccessor` functions required

---

src/config.ts
src/index.ts
src/modules/Points/fill-sampled-nodes.frag
src/modules/Points/fill-sampled-nodes.vert
src/modules/Points/index.ts
src/variables.ts

This PR adds a new method called `getSampledNodePositionsMap`. This method allows getting a map of the X and Y coordinates of a sample of nodes that are evenly distributed on the screen.

Node Sampling

---

src/modules/Points/index.ts

Previously, when nodes had initial positions with negative X or Y values, the Many Body force pushed these nodes towards the left or right boundaries. This issue occurred because the boundaries were simulated in a space from 0 to `spaceSize` value.
We decided to rescale the initial coordinates of the nodes to fit the simulation space while preserving the proportion. This ensures that nodes with negative initial positions are correctly handled and prevents them from being pushed to the boundaries.

Rescale Initial Node Positions

---

src/index.ts
src/modules/Points/index.ts
src/modules/Points/size-buffer.ts

This is done to efficiently store and access the node sizes without the need to recalculate them every time they are needed.

Storing the node size in a Float32Array

---

package-lock.json
package.json
src/config.ts
src/index.ts
src/modules/Zoom/index.ts
src/variables.ts

New config properties:
- `fitViewOnInit`
- `fitViewDelay`
- `fitViewByNodesInRect`

Fit Nodes in the Scene on Initialization

---

package-lock.json
package.json

This pull request fixes an error occurring when building the library with node js version 20 and ttypescript version 1.5.13. The error was:
Upgrading ttypescript to version 1.5.15 resolved the issue.

Bump ttypescript from 1.5.13 to 1.5.15

---

src/config.ts
src/index.ts
src/variables.ts

* The `initialZoomLevel` configuration parameter is now `undefined` by default.
* If `initialZoomLevel` is set, the view will not be fit to the initial zoom level.

Update initial zoom behavior

---

src/index.ts

The configuration property `backgroundColor` now supports color with transparency in the format `rgba(r, g, b, a)`, where `a` is the opacity value. For example, `rgba(0, 0, 0, 0)` would set the background color to black with no opacity.
🙏 This change was inspired by an issue raised by [miklevin](https://github.com/miklevin) in the cosmograph-issues repository (https://github.com/cosmograph-org/cosmograph-issues/issues/14).

Add support for background color with transparency

---

src/modules/Points/draw-points.vert
src/modules/Points/find-hovered-point.vert
src/modules/Points/find-points-on-area-selection.frag
src/modules/Points/index.ts

https://github.com/cosmograph-org/cosmos/assets/8654114/afc395ea-77b4-449f-a0e9-b2371a1d7aea

Improved point detection accuracy on mouse hover

---

src/index.ts
src/modules/Points/index.ts
src/modules/Zoom/index.ts

- **Canvas Resizing:** Previously, centering of the view was lost when resizing the canvas. Now, the centering is saved during resizing.
- **Paddings when Fitting the View:** When fitting the view, the paddings are now taken into account as a percentage of the view size.
- **Prevent Maximum call stack size exceeded:** Calculating the minimum and maximum values using `Math.min` and `Math.max` with spread operators can lead to Maximum call stack size exceeded error, especially when dealing with large arrays. To address this issue, the d3-array `extend` method is used instead, which is more memory-efficient and provides the same functionality.

Improvements to Canvas Resizing, View Fitting, and Memory Management

---

package-lock.json
package.json
src/index.ts
src/modules/Points/index.ts

This PR adds the `dontRescale` parameter as the second argument to the `setPointPositions` method, allowing one-time skip of rescaling.

Allowing a one-time rescaling skip during the `setPointPositions` call

---

package-lock.json
package.json
src/config.ts
src/index.ts
src/modules/Lines/index.ts

This PR refactors the update mechanism in the Graph class by replacing the previous `_has*Changed` boolean flags with more descriptive `_needs*Update` flags. Setter methods are updated to set all relevant flags, ensuring that dependent updates (such as links and forces when point positions change) are properly triggered.
Additional Change:
Clarified the documentation for the `initialZoomLevel` and `fitViewOnInit` config properties.

Refactor Graph Update Flags and Improve Dependency Handling for Graph Updates

---

src/index.ts
src/modules/GraphData/index.ts
src/modules/Points/draw-points.frag
src/modules/Points/draw-points.vert
src/modules/Points/index.ts
src/stories/3. api-reference.mdx
src/stories/shapes.stories.ts
src/stories/shapes/all-shapes/index.ts

- **PointShape enum** with 8 shape types:
- Circle (default)
- Square  
- Triangle
- Diamond
- Pentagon
- Hexagon
- Star
- Cross
- **New API method**: `setPointShapes(pointShapes: Float32Array)`
```javascript
import { Graph, PointShape } from '@cosmos.gl/graph'
graph.setPointShapes(new Float32Array([
PointShape.Circle,   // Regular nodes
PointShape.Star,     // Important nodes
PointShape.Triangle, // Special categories
PointShape.Diamond   // Key connectors
]));
```

Add support for multiple point shapes with 8 shape types

---

src/config.ts
src/index.ts
src/stories/2. configuration.mdx

Adds a new configuration property `fitViewByPointIndices` that allows users to fit the view to specific points by their indices when `fitViewOnInit` is enabled.
```typescript
const graph = new Graph(div, {
fitViewOnInit: true,
fitViewByPointIndices: [0, 5, 10, 15], // Focus on specific points
fitViewDuration: 500,
fitViewPadding: 0.2
})
```
When `fitViewOnInit` is `true`, the priority order is:
1. `fitViewByPointIndices` (if provided) - **NEW**
2. `fitViewByPointsInRect` (if provided)
3. `fitView()` (default - all points)

Add `fitViewByPointIndices` configuration property
